services:
  postgres:
    image: postgres:18
    container_name: sentinel-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - sentinel_postgres_data:/var/lib/postgresql

  redis:
    image: redis:8
    container_name: sentinel-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - sentinel_redis_data:/data

  api1:
    build:
      context: ./backend
    container_name: sentinel-api-1
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379
    expose:
      - "8000"
    depends_on:
      - postgres
      - redis

  api2:
    build:
      context: ./backend
    container_name: sentinel-api-2
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379
    expose:
      - "8000"
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:alpine
    container_name: sentinel-nginx
    restart: unless-stopped
    ports:
      - "${API_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2

  worker:
    build:
      context: ./worker
    restart: unless-stopped
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis

volumes:
  sentinel_postgres_data:
  sentinel_redis_data: